env:
  browser: true
  amd: true
  node: true
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "react"
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  '@typescript-eslint/no-var-requires': 0
